// <auto-generated />
namespace Leaderboard.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstNameLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstNameLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201306152058483_FirstNameLastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
